feat(Project):create React project
Ogurchik-007/spare-part-selling pull request #12
Opened 2022-03-09 13:20 UTC by Ogurchik-007

2022-03-09 15:24 UTC, Dendy-D requested changes
Кроме всего прочего, создай frontend и backend директории, создай базувую архитектуру, типо components папки  в которую можешь засунуть App, и для App тоже создать папку можно, И ты ч удалил index.css файл чтоли? Если да то восстанови его, и можешь пока пустым оставить, И потом еще качни sass и переименнуй css файлы yf .module.scss

2022-03-10 01:21 UTC, Ogurchik-007 commented on frontend/package.json
> +    "@testing-library/jest-dom": "^5.14.1",
Не понял что ты имел ввиду

2022-03-10 10:03 UTC, Dendy-D commented on frontend/package.json
> +    "@testing-library/jest-dom": "^5.14.1",
Ну есть dependensis и devDependensis, все что я указал лучше в dev добавить, тоесть переустановить просто

2022-03-11 14:20 UTC, Dendy-D commented on frontend/package.json
> +    "typescript": "^4.5.4",
ts тож в devDependencies

2022-03-11 14:30 UTC, Dendy-D approved these changes

2022-03-11 14:30 UTC, merged